# Generated by Django 6.0.6 on 2026-07-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningsession',
            name='reward_rate',
            field=models.DecimalField(decimal_places=8, default='10.00000000', max_digits=20),
        ),
        migrations.AlterField(
            model_name='miningsession',
            name='reward',
            field=models.DecimalField(decimal_places=8, default='0.00000000', max_digits=20),
        ),
    ]
