# Generated by Django 6.0.6 on 2026-07-14 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_miningsession_reward_rate_alter_miningsession_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('pool_fee_pct', models.DecimalField(decimal_places=2, default='1.00', help_text='Pool operator fee percentage (e.g. 1.00 = 1%).', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mining Pool',
            },
        ),
        migrations.AddField(
            model_name='miningsession',
            name='hash_rate_snapshot',
            field=models.PositiveIntegerField(default=10, help_text='MH/s at the time this session started.'),
        ),
        migrations.AddField(
            model_name='miningsession',
            name='pool',
            field=models.ForeignKey(blank=True, help_text='Pool this session contributed to (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mining.miningpool'),
        ),
        migrations.CreateModel(
            name='MiningRig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('BASIC', 'Basic CPU'), ('GPU', 'GPU Rig'), ('ASIC', 'ASIC Miner'), ('QUANTUM', 'Quantum Rig')], default='BASIC', help_text='Current hardware tier. Higher tier = more hash rate = more reward.', max_length=16)),
                ('hash_rate', models.PositiveIntegerField(default=10, help_text='Hash rate in MH/s.')),
                ('total_upgrades', models.PositiveIntegerField(default=0, help_text='Number of times this rig has been upgraded.')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('upgraded_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mining_rig', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mining Rig',
            },
        ),
        migrations.AddField(
            model_name='miningsession',
            name='rig',
            field=models.ForeignKey(blank=True, help_text='Rig used for this session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mining.miningrig'),
        ),
        migrations.CreateModel(
            name='PoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rig_hash_rate_snapshot', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mining.miningpool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pool_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pool Membership',
            },
        ),
    ]
