# Generated by Django 6.0.6 on 2026-07-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0003_miningpool_miningsession_hash_rate_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningsession',
            name='pow_attempts',
            field=models.BigIntegerField(default=0, help_text='Total hashes tried before finding solution.'),
        ),
        migrations.AddField(
            model_name='miningsession',
            name='pow_hash',
            field=models.CharField(blank=True, default='', help_text="Block hash produced by this miner's PoW solution.", max_length=64),
        ),
        migrations.AddField(
            model_name='miningsession',
            name='pow_nonce',
            field=models.BigIntegerField(default=0, help_text='Winning nonce found during PoW race.'),
        ),
        migrations.AlterField(
            model_name='miningrig',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basic CPU'), ('GPU', 'GPU Rig'), ('ASIC', 'ASIC Miner'), ('QUANTUM', 'Quantum Rig')], default='BASIC', help_text='Current hardware tier. Higher tier = more hash rate = faster PoW solve.', max_length=16),
        ),
    ]
