# Generated by Django 6.0.7 on 2026-07-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('login_locked', 'Login Locked'), ('login_2fa_failed', 'Login 2FA Failed'), ('logout', 'Logout'), ('register', 'Register'), ('email_verify_sent', 'Email Verification Sent'), ('email_verified', 'Email Verified'), ('email_verify_failed', 'Email Verification Failed'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_done', 'Password Reset Completed'), ('password_reset_failed', 'Password Reset Failed'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('mining_start', 'Mining Start'), ('mining_claim', 'Mining Claim'), ('tx_created', 'Transaction Created'), ('tx_confirmed', 'Transaction Confirmed'), ('tx_failed', 'Transaction Failed'), ('token_expired', 'Token Expired')], db_index=True, max_length=50),
        ),
    ]
