# Generated by Django 6.0.6 on 2026-07-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_index', models.PositiveIntegerField(db_index=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(max_length=64)),
                ('merkle_root', models.CharField(max_length=64)),
                ('nonce', models.BigIntegerField(default=0)),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('difficulty', models.PositiveIntegerField(default=2)),
                ('miner_address', models.CharField(blank=True, default='', max_length=67)),
                ('reward', models.DecimalField(decimal_places=8, default='0.00000000', max_digits=20)),
                ('tx_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-block_index'],
            },
        ),
    ]
