# Generated by Django 6.0.6 on 2026-07-13 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_index',
            field=models.PositiveIntegerField(db_index=True, help_text='Block height in the chain. Genesis block is 0.', unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Database insertion timestamp (differs from block timestamp only if the block was imported rather than mined locally).'),
        ),
        migrations.AlterField(
            model_name='block',
            name='difficulty',
            field=models.PositiveIntegerField(default=2, help_text='Number of leading zero hex chars required in a valid hash. Bitcoin adjusts this every 2,016 blocks.'),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(db_index=True, help_text="Double-SHA256 hash of this block's header fields (index + timestamp + merkle_root + previous_hash + nonce).", max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='merkle_root',
            field=models.CharField(help_text='Root of the Merkle tree built from all transaction hashes in this block. Allows efficient tx membership proofs.', max_length=64),
        ),
        migrations.AlterField(
            model_name='block',
            name='miner_address',
            field=models.CharField(blank=True, default='', help_text='SIKKA wallet address of the miner who solved the PoW puzzle.', max_length=67),
        ),
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.BigIntegerField(default=0, help_text='The value iterated during mining until the hash satisfies the difficulty target.'),
        ),
        migrations.AlterField(
            model_name='block',
            name='previous_hash',
            field=models.CharField(help_text='Double-SHA256 hash of the previous block header. All zeros for the genesis block.', max_length=64),
        ),
        migrations.AlterField(
            model_name='block',
            name='reward',
            field=models.DecimalField(decimal_places=8, default='0.00000000', help_text='SKA tokens awarded to the miner via the coinbase transaction.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='UTC timestamp when this block was accepted into the chain.'),
        ),
        migrations.AlterField(
            model_name='block',
            name='tx_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of transactions included in this block.'),
        ),
    ]
