# Generated by Django 6.0.6 on 2026-07-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_alter_block_block_index_alter_block_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='timestamp_raw',
            field=models.CharField(blank=True, default='', help_text='Original timestamp string used during mining (str(time.time()) for non-genesis blocks). Preserved to allow exact hash recomputation during chain validation.', max_length=32),
        ),
    ]
