# Generated by Django 6.0.7 on 2026-07-21 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0006_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('REWARD_REQUEST', 'Reward Requested'), ('REWARD_APPROVED', 'Reward Approved'), ('REWARD_REJECTED', 'Reward Rejected'), ('QUOTA_WARNING', 'Quota Warning'), ('ORG_VERIFICATION', 'University Verification'), ('SYSTEM', 'System Announcement')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='transactions.reward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
