# Generated by Django 6.0.6 on 2026-07-12 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='block_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('COINBASE', 'Mining Reward'), ('TRANSFER', 'Transfer')], default='TRANSFER', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_address',
            field=models.CharField(blank=True, db_index=True, default='', max_length=67),
        ),
    ]
