# Generated by Django 6.0.6 on 2026-07-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
