# Generated by Django 6.0.7 on 2026-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('COINBASE', 'Mining Reward'), ('TRANSFER', 'Transfer'), ('REWARD', 'University Reward')], default='TRANSFER', max_length=16),
        ),
    ]
