# Generated by Django 6.0.7 on 2026-07-21 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_tx_type'),
        ('wallet', '0007_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('HACKATHON', 'Hackathon'), ('CERTIFICATION', 'Certification'), ('PLACEMENT', 'Placement'), ('EVENT', 'Event'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_issued', to='wallet.organisation')),
                ('student_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_received', to='wallet.wallet')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_detail', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
