# Generated by Django 6.0.6 on 2026-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='private_key',
            field=models.TextField(blank=True, default='', help_text='⚠️  FOR EDUCATIONAL / DEMO USE ONLY. Never store unencrypted private keys in production. Consider encrypting at rest (e.g. django-fernet-fields) before deployment.'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='public_key',
            field=models.TextField(blank=True, default='', help_text='PEM-encoded or hex-encoded public key for this wallet.'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, default='', help_text='Unique on-chain address derived from the public key (hex string). Populated by a pre-save signal or service layer.', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', help_text='Lifecycle status of this wallet.', max_length=16),
        ),
    ]
