# Generated by Django 6.0.6 on 2026-07-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_private_key_wallet_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.TextField(blank=True, default='', help_text='FOR EDUCATIONAL PURPOSES ONLY. In production blockchain systems, private keys are generated and stored securely on the client side (e.g., MetaMask or hardware wallets) and are never stored in plaintext on the server.'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, default='', help_text='Unique blockchain wallet address. Generated automatically by the wallet service during wallet creation.', max_length=64, unique=True),
        ),
    ]
