# Generated by Django 6.0.6 on 2026-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_private_key_alter_wallet_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, default='', help_text='Unique blockchain wallet address. Generated automatically by the wallet service during wallet creation.', max_length=67, unique=True),
        ),
    ]
