# Generated by Django 6.0.6 on 2026-07-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallet_nonce_alter_wallet_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.TextField(blank=True, default='', help_text='FOR EDUCATIONAL PURPOSES ONLY. In production, private keys are never stored server-side.'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='public_key',
            field=models.TextField(blank=True, default='', help_text='PEM-encoded public key for this wallet.'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=16),
        ),
    ]
