# Generated by Django 6.0.7 on 2026-07-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_private_key_alter_wallet_public_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('reward_quota', models.DecimalField(decimal_places=8, default='10000.00000000', max_digits=20)),
                ('quota_used', models.DecimalField(decimal_places=8, default='0.00000000', max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='wallet.wallet')),
            ],
        ),
    ]
