# Generated by Django 6.0.7 on 2026-07-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
